#!/bin/bash
gawk '
(NR == 1) {
  for (i = 0; ++i <= NF; )
    items[i] = $i;
}
(NR > 1) {
  for (i = k = 0; ++i <= NF; ) {
    if (($i == "T") || ($i == "t") || ($i == "1")) {
      if (k++ > 0) printf(" ");
      printf("%s", items[i]);
    }
  }
  printf("\n");
}' $1 > $2
